version: '3.3'

services:

  spring-boot-admin:
    image: fredericci/spring-boot-admin:latest
    ports:
      - 8080:8080
    environment:
      - EUREKA_SERVER_LIST=http://eureka-server-01:8761/eureka/,http://eureka-server-02:8762/eureka/

  eureka-server-01:
    image: fredericci/eureka-server:latest
    environment:
      - SERVER_PORT=8761
      - SPRING_BOOT_ADMIN_URL=http://spring-boot-admin:8080
    ports:
       - 8761:8761

  eureka-server-02:
    image: fredericci/eureka-server:latest
    environment:
      - SERVER_PORT=8762
      - SPRING_BOOT_ADMIN_URL=http://spring-boot-admin:8080
    ports:
      - 8762:8762

  config-server:
    image: fredericci/spring-config-server:latest
    ports:
      - 8888:8888
    environment:
      - SPRING_BOOT_ADMIN_URL=http://spring-boot-admin:8080
      - EUREKA_SERVER_LIST=http://eureka-server-01:8761/eureka/,http://eureka-server-02:8762/eureka/